name: Validate Config

on:
  pull_request:
    branches:
      - '*'

jobs:
  validate_config:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install configparser

    - name: Inject API_KEY and API_SECRET into config.ini
      run: |
        echo -e "[keys]\napi_key=${{ secrets.API_KEY }}\napi_secret=${{ secrets.API_SECRET }}" > examples/config.ini

    - name: Validate config.ini
      run: python examples/validate_config.py
